//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpDay1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpDay1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 156
        ///176
        ///175
        ///176
        ///183
        ///157
        ///150
        ///153
        ///154
        ///170
        ///162
        ///167
        ///170
        ///188
        ///190
        ///194
        ///196
        ///198
        ///202
        ///203
        ///187
        ///189
        ///194
        ///213
        ///216
        ///217
        ///224
        ///217
        ///216
        ///224
        ///237
        ///251
        ///259
        ///260
        ///292
        ///312
        ///313
        ///319
        ///315
        ///316
        ///324
        ///330
        ///331
        ///346
        ///361
        ///388
        ///373
        ///363
        ///338
        ///342
        ///337
        ///331
        ///333
        ///328
        ///329
        ///335
        ///336
        ///334
        ///332
        ///333
        ///337
        ///338
        ///345
        ///344
        ///342
        ///345
        ///344
        ///320
        ///343
        ///346
        ///347
        ///339
        ///363
        ///349
        ///362
        ///359
        ///373
        ///362
        ///363
        ///356
        ///360
        ///367
        ///368
        ///369
        ///370
        ///362
        ///366
        ///367
        ///382
        ///376
        ///393
        ///404
        ///403
        ///405
        ///404
        ///437
        ///447
        ///448
        ///447
        ///448
        ///456
        ///457
        ///45 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
